# For local dev only
version: '3'

services:
  neo4j:
    image: neo4j:5.9
    container_name: 'neo4j-dev'
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
    environment:
      - NEO4J_dbms_memory_pagecache_size=4G
      - NEO4J_AUTH=neo4j/drink-saturn-clara-radio-greek-8482
      - apoc.export.file.enabled=true
      - apoc.import.file.enabled=true
      - apoc.import.file.use_neo4j_config=true 
      - NEO4J_PLUGINS=\[\"apoc\"\]
    restart: on-failure